version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: customers_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    networks:
      - customers
  customers_backend:
    build: ./customers
    ports:
      - "8001:8000"
    depends_on:
      - db
    networks:
      - customers
      - users
  customers_queue:
    build: ./customers
    command: >
      sh -c "python manage.py wait_for_db
      && python consumer.py"
    depends_on:
      - db
    networks:
      - customers
networks:
  customers:
  users:
    external:
      name: users