version: '3.8'
gateway:
  build: ./gateway
  ports:
    - "8007:8000"
  networks:
    - authorization
    - catalog
    - customers
    - entries
    - exits
    - stock
    - suppliers
    rede_principal:
      external: true