version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - catalog
  catalog_backend:
    build: ./catalog
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - catalog
      - users
  catalog_queue:
    build: ./catalog
    command: >
      sh -c "python manage.py wait_for_db
      && python consumer.py"
    depends_on:
      - db
    networks:
      - catalog
networks:
  rede_principal:
    external: true