version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: exits_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5435:5432"
    networks:
      - exits
  exits_backend:
    build: ./exits
    ports:
      - "8003:8000"
    depends_on:
      - db
    networks:
      - exits
      - users
  exits_queue:
    build: ./exits
    command: >
      sh -c "python manage.py wait_for_db
      && python consumer.py"
    depends_on:
      - db
    networks:
      - entries
networks:
  exits:
  users:
    external:
      name: users