version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: entries_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    networks:
      - entries
  entries_backend:
    build: ./entries
    ports:
      - "8002:8000"
    depends_on:
      - db
    networks:
      - entries
      - users
  entries_queue:
    build: ./entries
    command: >
      sh -c "python manage.py wait_for_db
      && python consumer.py"
    depends_on:
      - db
    networks:
      - entries
networks:
  rede_principal:
    external: true